# Site settings
title: gee punya blog
header-img: img/home-bg.jpg
email: ghuuf_rony@yahoo.com
copyright_name: gee/gee.github.io/t.informatika
description: "teknik informatika universitas lampung 016"
baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://gee.informatika.com"
twitter_username: @Oeny_R
github_username:  ghuffronyrezaldhygee
facebook_username:  ghuffrony rezaldhy ms
email_username:  ghuff_rony@yahoo.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
